### ISSUE TITLE
Добавить шорткаты для npm run build-*projectname* и npm run start-*projectname*

### ISSUE THREAD

**Issue by moetelo** [Shifu462/chat#1]
Хочется, чтобы можно было из корневой директории можно было такие команды писать, не заходя в `packages/projectname`.

**Comment by Mishka1337** [comment]
https://habr.com/ru/company/ruvds/blog/458504/
5 пункт

**Comment by moetelo** [comment]
@Mishka1337 
Спасибо!

**Comment by moetelo** [comment]
@Mishka1337 
вероятно тут вообще желательно вебпак прикрутить
https://github.com/dan-kez/lerna-webpack-example

**Comment by moetelo** [comment]
Было добавлено вот в этом коммите: https://github.com/misha-mikhail/messenger/commit/5cc72a44a8a670d12a03622b88f0756bbaf9715e
