### ISSUE TITLE
Логгирование на сервере

### ISSUE THREAD

**Issue by moetelo** [Shifu462/chat#22]
- [x] логгировать реквесты в консоль и в .log-файл
- [x] добавить директорию с логами в .gitignore
- [x] нужны левелы логгирования, типа Info, Warning, Error.
- [ ] нужна конфигурация логгирования, чтобы можно было не изменяя код настроить логгирование. Отключить запись в файл, к примеру, или поменять левел логгирования.

**Comment by moetelo** [comment]
`app.use(logger())` ?

**Comment by Mishka1337** [comment]
https://www.npmjs.com/package/koa-logger
вот какая-то такая залупа есть

**Comment by Mishka1337** [comment]
только он без уровней логгирования, и с выводом в файл нужно потупить
