### ISSUE TITLE
начать пилить нормальные ендпоинты

### ISSUE THREAD

**Issue by Mishka1337** [Shifu462/chat#3]
да

**Comment by moetelo** [comment]
эту ищью нужно декомпозировать и после этого закрыть

**упд:**
эту ищью декомпозировать не нужно. договорились создать майлстоун под эндпоинты, а в рамках этой ищью я НАЧАЛ собственно

и Миша тоже начал 
https://github.com/Shifu462/chat/commit/e0a6b007d66445eed6338682ac44a62c79ee0946

**Comment by moetelo** [comment]
https://github.com/Shifu462/chat/milestone/1
