### ISSUE TITLE
Аутентификация

### ISSUE THREAD

**Issue by Mishka1337** [Shifu462/chat#4]
Нужно прикрутить аутентификацию, хэширование паролей и так далее.

- [x] POST /auth/login
- [x] POST /auth/register
- [x] authorizationChecker чтобы использовать [атрибут @Authorized](https://github.com/typestack/routing-controllers#authorized-decorator)
- [x] currentUserChecker чтобы получать юзера изнутри экшна [через @CurrentUser](https://github.com/typestack/routing-controllers#currentuser-decorator)
- [x] прибрать за собой тудушки

ветка auth: https://github.com/misha-mikhail/messenger/tree/auth

**Comment by moetelo** [comment]
нужно создать из этого майлстоун! после этого эту ищью закрыть

**Comment by moetelo** [comment]
Можно, но не очень-то и нужно.

**Comment by moetelo** [comment]
Эта задача очень сильно блокирует остальные задачи по эндпоинтам.
